---
title: "STA035B Homework 0, due: 4/8, 9pm"
author: "Akira Horiguchi"
output: pdf_document
geometry:
  - top=15mm
  - bottom=25mm
  - left=12mm
  - right=12mm
---

## Instructions
Upload a PDF file, named with your UC Davis email ID and homework number (e.g., ahoriguchi_hw1.pdf), to Gradescope (accessible through Canvas). You will give the commands to answer each question in its own code block, which will also produce output that will be automatically embedded in the output file.  All code used to answer the question must be supplied, as well as written statements where appropriate. 

All code used to produce your results must be shown in your PDF file (e.g., do not use `echo = FALSE` or `include = FALSE` as options anywhere). Rmd/qmd files do not need to be submitted, but may be requested by the TA and must be available when the assignment is submitted.

Students may choose to collaborate with each other on the homework, but must clearly indicate with whom they collaborated.

\newpage 

### Problem 1

Read either the [R markdown tutorial](https://rmarkdown.rstudio.com/lesson-1.html) or the [Quarto tutorial](https://quarto.org/docs/get-started/hello/rstudio.html). (If you have no preference between R Markdown and Quarto, I would recommend you use Quarto.) Create and submit a PDF file according to the instructions above.

(Hint: take advantage of your lab section, where you can ask your TA for help.)